version: '3.7'
services:
  currikiprod-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: currikiprod-elastic
    environment:
      - node.name=currikiprod-elastic
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - currikiprod-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - currikinetwork


#   kib01:
#     image: docker.elastic.co/kibana/kibana:7.11.1
#     container_name: kib01
#     ports:
#       - 5601:5601
#     environment:
#       ELASTICSEARCH_URL: http://es01:9200
#       ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
#       ELASTICSEARCH_USERNAME: elastic
#       ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
#     networks:
#       - elastic

volumes: #provide volume
  currikiprod-elasticsearch:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: /mnt/DBData/currikiprod-elasticsearch
networks:
  currikinetwork:
    name: currikinetwork
    external: true
